# Generated by Django 3.2.9 on 2021-11-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clab_name', models.CharField(max_length=50)),
                ('coutry', models.CharField(max_length=3)),
                ('rating', models.IntegerField(max_length=3)),
            ],
        ),
    ]
