# Generated by Django 3.2.9 on 2021-11-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperLeague', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clubs',
            new_name='Club',
        ),
    ]
