# Generated by Django 3.2.9 on 2021-11-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperLeague', '0002_rename_clubs_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='clab_name',
            new_name='club_name',
        ),
    ]
