# Generated by Django 3.2.9 on 2021-11-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperLeague', '0006_delete_tournament_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament_table',
            fields=[
                ('position', models.AutoField(primary_key=True, serialize=False)),
                ('game', models.IntegerField(default=0, max_length=3)),
                ('goal_difference', models.IntegerField(default=0, max_length=3)),
                ('point', models.IntegerField(default=0, max_length=3)),
            ],
        ),
    ]
