# Generated by Django 3.2.9 on 2021-11-21 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SuperLeague', '0007_tournament_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament_table',
            name='club',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='SuperLeague.club'),
            preserve_default=False,
        ),
    ]
