# Generated by Django 3.2.9 on 2021-11-21 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SuperLeague', '0011_auto_20211121_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tour_one',
            name='goal_away',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tour_one',
            name='goal_home',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tour_one',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperLeague.club'),
        ),
    ]
