# Generated by Django 3.2.9 on 2021-11-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperLeague', '0013_tournament_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament_table',
            name='club_ptr',
        ),
    ]
