# Generated by Django 3.2.9 on 2021-11-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperLeague', '0014_remove_tournament_table_club_ptr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('poz', models.CharField(max_length=10)),
            ],
        ),
    ]
